Update RepositoryTrait.php
We will got an error exception if we didn't set $templateName variable in transformer class file

In my mind, we don't need to set $templateName in repository, so why we need put repository class into finding-loop?

Error: Cannot use object of type App\Repositories\...Repository as array